vanillabrain/vanillameta

- frontend-web/src/api/componentService.ts
- frontend-web/src/api/dashboardService.ts
- frontend-web/src/api/templateService.ts
- frontend-web/src/api/widgetService.ts
> [feat] add service call files

- .idea/modules.xml
- .idea/webResources.xml
- backend-api/backend-api.iml
- frontend-web/frontend-web.iml
> [global] Update module settings

- frontend-web/src/modules/linechart/LineChart.tsx
- frontend-web/src/modules/piechart/PieChart.tsx
- frontend-web/src/modules/utils/chartUtil.ts
add to change chart legend position
> [feat] add chart legend position property

- frontend-web/src/components/button/DialogAlertButton.tsx
- frontend-web/src/pages/Dashboard/DashboardModify/index.tsx
> 다이얼로그 이벤트 추가

- frontend-web/src/components/form/ColorPickerForm.tsx
- frontend-web/src/components/form/SelectForm.tsx
- frontend-web/src/constant/index.ts
- frontend-web/src/data/componentList.json
- frontend-web/src/modules/ board/NumericBoard.tsx
- frontend-web/src/modules/ board/TableBoard.tsx
- frontend-web/src/modules/linechart/LineChart.tsx
- frontend-web/src/modules/utils/chartUtil.ts
- frontend-web/src/pages/Widget/WidgetCreate/WidgetAttributeSelect.tsx
- frontend-web/src/pages/Widget/WidgetCreate/index.tsx
- frontend-web/src/widget/settings/LineChartSetting.tsx
- frontend-web/src/widget/settings/NumericBoardSetting.tsx
- frontend-web/src/widget/settings/TableBoardSetting.tsx
add Numeric Board, Table Board
> [feat] add Numeric Board, Table Board 

- backend-api/src/main.ts
- backend-api/src/nest-utils/http-exception.filter.ts
- backend-api/src/template/dto/create-template.dto.ts
- backend-api/src/template/template.controller.ts
- backend-api/src/template/template.service.ts
1. template 구조 변경(template_item table 추가)
2. api error 공통처리
> [feat] template 구조 변경, api error 공통처리

- backend-api/.prettierrc
- backend-api/src/database/connection/connection.service.spec.ts
- backend-api/src/database/connection/connection.service.ts
- backend-api/src/database/database.controller.ts
- backend-api/src/database/database.module.ts
- backend-api/src/database/database.service.ts
>  Add connection.service.ts

- frontend-web/src/pages/Dashboard/DashboardModify/index.tsx
변경된 ConfirmCancelButton 속성에 맞춰서 수정
> 변경된 ConfirmCancelButton 속성에 맞춰서 수정

- frontend-web/.env
- frontend-web/.env.development
- frontend-web/src/api/componentService.ts
- frontend-web/src/api/dashboardService.ts
- frontend-web/src/api/templateService.ts
- frontend-web/src/api/widgetService.ts
- frontend-web/src/pages/Dashboard/Components/RecommendDashboardPopup.tsx
> 서비스 api 대문자 수정

- .idea/modules.xml
- frontend-web/.env.local
- frontend-web/src/api/type/index.ts
- frontend-web/src/api/widgetService.ts
- frontend-web/src/components/BoardListItem.tsx
- frontend-web/src/pages/Dashboard/DashboardView/index.tsx
- frontend-web/src/pages/Dashboard/index.tsx
- frontend-web/src/pages/Widget/WidgetView/index.tsx
- frontend-web/src/pages/Widget/index.tsx
- frontend-web/src/router/index.tsx
> [feat] 서비스연결중

- frontend-web/src/layouts/Header/Header.tsx
- frontend-web/src/pages/Dashboard/DashboardModify/index.tsx
- frontend-web/src/pages/Dashboard/index.tsx
> 변경된 parameter 에 맞게 수정

- .gitignore
- frontend-web/src/components/ImgCardList.tsx
- frontend-web/src/components/PageContainer.tsx
- frontend-web/src/components/PageTitleBox.tsx
- frontend-web/src/layouts/Footer/Footer.tsx
- frontend-web/src/layouts/Layout.tsx
- frontend-web/src/modules/linechart/LineChart.tsx
- frontend-web/src/pages/Widget/WidgetCreate/WidgetAttributeSelect.tsx
- frontend-web/src/pages/Widget/WidgetCreate/WidgetTypeSelect.tsx
- frontend-web/src/pages/Widget/WidgetCreate/index.tsx
- frontend-web/src/pages/Widget/WidgetModify/index.tsx
- frontend-web/src/pages/Widget/WidgetView/index.tsx
- frontend-web/src/widget/wrapper/WidgetWrapper.tsx
> [feat] add data service to widget

- frontend-web/src/api/dashboardService.ts
- frontend-web/src/api/templateService.ts
- frontend-web/src/constant/index.ts
- frontend-web/src/pages/Dashboard/Components/AddWidgetPopup.tsx
- frontend-web/src/pages/Dashboard/Components/RecommendDashboardPopup.tsx
- frontend-web/src/pages/Dashboard/DashboardModify/index.tsx
- frontend-web/src/pages/Dashboard/DashboardView/index.tsx
- frontend-web/src/pages/Dashboard/index.tsx
- 조회, 수정, 등록, 삭제 연결 템플릿 서비스 연결
- 템플릿 추천 목록 조회, 템플릿 추천 대시보드 정보 조회 변경된 속성값으로 맵핑
> 대시보드 서비스 연결

- frontend-web/src/api/datasetService.ts
- frontend-web/src/pages/Data/DataLayout.tsx
- frontend-web/src/pages/Data/DataSet/index.tsx
- frontend-web/src/router/index.tsx
connect Database service to UI
connect Dataset service to UI
> [feat] Add data page services

- frontend-web/src/api/databaseService.ts
- frontend-web/src/components/BoardListItem.tsx
- frontend-web/src/components/CardList.tsx
- frontend-web/src/components/PageContainer.tsx
- frontend-web/src/components/PageTitleBox.tsx
- frontend-web/src/components/TitleBox.tsx
- frontend-web/src/constant/index.ts
- frontend-web/src/layouts/Layout.tsx
- frontend-web/src/pages/Dashboard/DashboardView/index.tsx
- frontend-web/src/pages/Data/DataLayout.tsx
- frontend-web/src/pages/Widget/WidgetCreate/WidgetAttributeSelect.tsx
- frontend-web/src/pages/Widget/WidgetCreate/WidgetDataSelect.tsx
- frontend-web/src/pages/Widget/WidgetCreate/index.tsx
- frontend-web/src/pages/Widget/WidgetModify/index.tsx
- frontend-web/src/pages/Widget/WidgetView/index.tsx
- frontend-web/src/router/index.tsx
- frontend-web/src/widget/wrapper/WidgetSetting.tsx
- frontend-web/src/widget/wrapper/WidgetViewer.tsx
- frontend-web/src/widget/wrapper/WidgetWrapper.tsx
Changed fake data calls to real data calls.
> Changed fake data calls to real data calls.

- backend-api/src/database/database.controller.ts
- backend-api/src/database/database.service.ts
- backend-api/src/database/dto/create-database.dto.ts
Modify database get response structure (Add datasetType column)
> [BE-database] Modify database get response structure (Add datasetType column)

- frontend-web/src/components/form/TextFieldForm.tsx
- frontend-web/src/pages/Widget/WidgetCreate/WidgetAttributeSelect.tsx
- frontend-web/src/pages/Widget/WidgetCreate/index.tsx
- frontend-web/src/pages/Widget/WidgetModify/index.tsx
- frontend-web/src/pages/Widget/WidgetView/index.tsx
- frontend-web/src/widget/wrapper/WidgetSetting.tsx
- frontend-web/src/widget/wrapper/WidgetWrapper.tsx
Modify textinput Korean processing
> Modify textinput Korean processing

- frontend-web/src/components/BoardListItem.tsx
- frontend-web/src/layouts/Header/Header.tsx
- frontend-web/src/layouts/Layout.tsx
- frontend-web/src/pages/Dashboard/DashboardView/index.tsx
> 위젯 상세 페이지 링크 오류 수정

- frontend-web/src/components/BoardListItem.tsx
- frontend-web/src/pages/Dashboard/DashboardModify/index.tsx
- frontend-web/src/pages/Data/Recommend/index.tsx
> Fix bug a tag in a tag

- frontend-web/src/pages/Dashboard/Components/RecommendDashboardPopup.tsx
- frontend-web/src/pages/Data/DataSource/form/DatabaseForm.tsx
- frontend-web/src/pages/Data/DataSource/index.tsx
- frontend-web/src/pages/Data/index.tsx
modify dashboard template page
> Modify dashboard template page

- frontend-web/src/router/index.tsx
> Modify router

- backend-api/serverless.yml
- backend-api/src/app.module.ts
- frontend-web/.env.development
> Update .env settings

- backend-api/src/serverless.ts
- frontend-web/package.json
> add origin setup

- backend-api/serverless.yml
> cors origin 업데이트

- backend-api/src/connection/connection.service.ts
- backend-api/src/database/database.service.ts
> fix cockroachdb config

- backend-api/src/connection/connection.service.ts
- backend-api/src/database/database.service.ts
style: update cockroach connections database.service
> style: update cockroach connections database.service

- backend-api/src/connection/connection.service.ts
- backend-api/src/database/database.service.ts
fix: database Invalid table name
> fix: database Invalid table name

- backend-api/src/connection/connection.service.ts
- backend-api/src/database/database.service.ts
feat: add snowflake connection
> feat: add snowflake connection

- backend-api/package-lock.json
- backend-api/src/connection/connection.service.ts
- backend-api/test/QTT-001/QTT-001-01.spec.ts
- package-lock.json
> feat: add QTT-001 testscript

- frontend-web/src/contexts/AuthContext.tsx
- frontend-web/src/pages/User/components/ProfileModify.tsx
- frontend-web/src/router/ProtectedRoute.tsx
> Fix authorization
